"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.create_user_response import CreateUserResponse

globals()["CreateUserResponse"] = CreateUserResponse
from checkedid.model.create_user_details_response import \
    CreateUserDetailsResponse


class TestCreateUserDetailsResponse(unittest.TestCase):
    """CreateUserDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserDetailsResponse(self):
        """Test CreateUserDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateUserDetailsResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
