"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import checkedid
from checkedid.api.invitation_api import InvitationApi  # noqa: E501


class TestInvitationApi(unittest.TestCase):
    """InvitationApi unit test stubs"""

    def setUp(self):
        self.api = InvitationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_invitees_create_invitations(self):
        """Test case for invitees_create_invitations

        Create Invitations  # noqa: E501
        """
        pass

    def test_invitees_delete_invitation(self):
        """Test case for invitees_delete_invitation

        Delete Invitation  # noqa: E501
        """
        pass

    def test_invitees_update_invitations(self):
        """Test case for invitees_update_invitations

        Update Invitations  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
