"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.activate_user_response import ActivateUserResponse

globals()["ActivateUserResponse"] = ActivateUserResponse
from checkedid.model.activate_users_response import ActivateUsersResponse


class TestActivateUsersResponse(unittest.TestCase):
    """ActivateUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivateUsersResponse(self):
        """Test ActivateUsersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivateUsersResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
