"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.activate_user_request import ActivateUserRequest


class TestActivateUserRequest(unittest.TestCase):
    """ActivateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivateUserRequest(self):
        """Test ActivateUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivateUserRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
