"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.create_user_request import CreateUserRequest

globals()["CreateUserRequest"] = CreateUserRequest
from checkedid.model.create_user_details import CreateUserDetails


class TestCreateUserDetails(unittest.TestCase):
    """CreateUserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserDetails(self):
        """Test CreateUserDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateUserDetails()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
