"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.update_user_response import UpdateUserResponse

globals()["UpdateUserResponse"] = UpdateUserResponse
from checkedid.model.update_user_details_response import \
    UpdateUserDetailsResponse


class TestUpdateUserDetailsResponse(unittest.TestCase):
    """UpdateUserDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateUserDetailsResponse(self):
        """Test UpdateUserDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateUserDetailsResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
