"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.activate_user_request import ActivateUserRequest

globals()["ActivateUserRequest"] = ActivateUserRequest
from checkedid.model.activate_users import ActivateUsers


class TestActivateUsers(unittest.TestCase):
    """ActivateUsers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivateUsers(self):
        """Test ActivateUsers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivateUsers()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
