"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.update_invitation_request import UpdateInvitationRequest

globals()["UpdateInvitationRequest"] = UpdateInvitationRequest
from checkedid.model.update_invitation_details import UpdateInvitationDetails


class TestUpdateInvitationDetails(unittest.TestCase):
    """UpdateInvitationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateInvitationDetails(self):
        """Test UpdateInvitationDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateInvitationDetails()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
