"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.invitation import Invitation

globals()["Invitation"] = Invitation
from checkedid.model.customer_details import CustomerDetails


class TestCustomerDetails(unittest.TestCase):
    """CustomerDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomerDetails(self):
        """Test CustomerDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomerDetails()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
