"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.create_invitation_request import CreateInvitationRequest

globals()["CreateInvitationRequest"] = CreateInvitationRequest
from checkedid.model.create_invitation_details import CreateInvitationDetails


class TestCreateInvitationDetails(unittest.TestCase):
    """CreateInvitationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateInvitationDetails(self):
        """Test CreateInvitationDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateInvitationDetails()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
