"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.report_data_v3 import ReportDataV3


class TestReportDataV3(unittest.TestCase):
    """ReportDataV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportDataV3(self):
        """Test ReportDataV3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportDataV3()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
