"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.user_request import UserRequest

globals()["UserRequest"] = UserRequest
from checkedid.model.update_user_details import UpdateUserDetails


class TestUpdateUserDetails(unittest.TestCase):
    """UpdateUserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateUserDetails(self):
        """Test UpdateUserDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateUserDetails()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
