"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import checkedid
from checkedid.model.report_response import ReportResponse


class TestReportResponse(unittest.TestCase):
    """ReportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportResponse(self):
        """Test ReportResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
