"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import checkedid
from checkedid.api.report_data_api import ReportDataApi  # noqa: E501


class TestReportDataApi(unittest.TestCase):
    """ReportDataApi unit test stubs"""

    def setUp(self):
        self.api = ReportDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_report_data_get_report_data_v2(self):
        """Test case for report_data_get_report_data_v2

        Get report details based on dossier number and scope  # noqa: E501
        """
        pass

    def test_report_data_get_report_data_v2_pdf(self):
        """Test case for report_data_get_report_data_v2_pdf

        Get report pdf based on dossier number  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
