"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from checkedid.exceptions import ApiAttributeError
from checkedid.model_utils import (ApiTypeError, ModelComposed,  # noqa: F401
                                   ModelNormal, ModelSimple, OpenApiModel,
                                   cached_property, change_keys_js_to_python,
                                   convert_js_args_to_python_args, date,
                                   datetime, file_type, none_type,
                                   validate_get_composed_info)


class ReportDataV3(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {}

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            "customer_code": (str,),  # noqa: E501
            "customer_name": (str,),  # noqa: E501
            "dossier_number": (str,),  # noqa: E501
            "employee_code": (str,),  # noqa: E501
            "employee_involved": (str,),  # noqa: E501
            "report_date_time": (str,),  # noqa: E501
            "executed_by": (str,),  # noqa: E501
            "report_result": (str,),  # noqa: E501
            "details": (str,),  # noqa: E501
            "details_message_code": (str,),  # noqa: E501
            "document_type": (str,),  # noqa: E501
            "document_type_code": (str,),  # noqa: E501
            "document_country": (str,),  # noqa: E501
            "document_number": (str,),  # noqa: E501
            "date_of_issue": (str,),  # noqa: E501
            "date_of_expiry": (str,),  # noqa: E501
            "authority": (str,),  # noqa: E501
            "first_name": (str,),  # noqa: E501
            "name": (str,),  # noqa: E501
            "sex": (str,),  # noqa: E501
            "date_of_birth": (str,),  # noqa: E501
            "place_of_birth": (str,),  # noqa: E501
            "personal_number": (str,),  # noqa: E501
            "nationality": (str,),  # noqa: E501
            "photo_id_chip": ([str],),  # noqa: E501
            "photo_holder": ([str],),  # noqa: E501
            "id_document_front": ([str],),  # noqa: E501
            "id_document_back": ([str],),  # noqa: E501
            "other_document": ([str],),  # noqa: E501
            "signature_from_id_document": (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "customer_code": "CustomerCode",  # noqa: E501
        "customer_name": "CustomerName",  # noqa: E501
        "dossier_number": "DossierNumber",  # noqa: E501
        "employee_code": "EmployeeCode",  # noqa: E501
        "employee_involved": "EmployeeInvolved",  # noqa: E501
        "report_date_time": "ReportDateTime",  # noqa: E501
        "executed_by": "ExecutedBy",  # noqa: E501
        "report_result": "ReportResult",  # noqa: E501
        "details": "Details",  # noqa: E501
        "details_message_code": "DetailsMessageCode",  # noqa: E501
        "document_type": "DocumentType",  # noqa: E501
        "document_type_code": "DocumentTypeCode",  # noqa: E501
        "document_country": "DocumentCountry",  # noqa: E501
        "document_number": "DocumentNumber",  # noqa: E501
        "date_of_issue": "DateOfIssue",  # noqa: E501
        "date_of_expiry": "DateOfExpiry",  # noqa: E501
        "authority": "Authority",  # noqa: E501
        "first_name": "FirstName",  # noqa: E501
        "name": "Name",  # noqa: E501
        "sex": "Sex",  # noqa: E501
        "date_of_birth": "DateOfBirth",  # noqa: E501
        "place_of_birth": "PlaceOfBirth",  # noqa: E501
        "personal_number": "PersonalNumber",  # noqa: E501
        "nationality": "Nationality",  # noqa: E501
        "photo_id_chip": "PhotoIdChip",  # noqa: E501
        "photo_holder": "PhotoHolder",  # noqa: E501
        "id_document_front": "IdDocumentFront",  # noqa: E501
        "id_document_back": "IdDocumentBack",  # noqa: E501
        "other_document": "OtherDocument",  # noqa: E501
        "signature_from_id_document": "SignatureFromIDDocument",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ReportDataV3 - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            customer_code (str): Customer Code. [optional]  # noqa: E501
            customer_name (str): Customer name. [optional]  # noqa: E501
            dossier_number (str): Dossier number of the report. [optional]  # noqa: E501
            employee_code (str): Employee Code. [optional]  # noqa: E501
            employee_involved (str): Employee Involved. [optional]  # noqa: E501
            report_date_time (str): Report Date Time. [optional]  # noqa: E501
            executed_by (str): Executed By. [optional]  # noqa: E501
            report_result (str): Result. [optional]  # noqa: E501
            details (str): Details. [optional]  # noqa: E501
            details_message_code (str): Details Message Code. [optional]  # noqa: E501
            document_type (str): Document Type. [optional]  # noqa: E501
            document_type_code (str): Document Code. [optional]  # noqa: E501
            document_country (str): Document Country. [optional]  # noqa: E501
            document_number (str): Document Number. [optional]  # noqa: E501
            date_of_issue (str): Date of Issue. [optional]  # noqa: E501
            date_of_expiry (str): Date of Expiry. [optional]  # noqa: E501
            authority (str): Authority. [optional]  # noqa: E501
            first_name (str): First Name. [optional]  # noqa: E501
            name (str): Name. [optional]  # noqa: E501
            sex (str): Sex. [optional]  # noqa: E501
            date_of_birth (str): Date of Birth. [optional]  # noqa: E501
            place_of_birth (str): Place of Birth. [optional]  # noqa: E501
            personal_number (str): Personal Number. [optional]  # noqa: E501
            nationality (str): Nationality. [optional]  # noqa: E501
            photo_id_chip ([str]): Photo Id Chip. [optional]  # noqa: E501
            photo_holder ([str]): Photo Holder. [optional]  # noqa: E501
            id_document_front ([str]): Front Document. [optional]  # noqa: E501
            id_document_back ([str]): Back Document. [optional]  # noqa: E501
            other_document ([str]): Other document. [optional]  # noqa: E501
            signature_from_id_document (str): Signature from ID Document. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", True)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = {
        "_data_store",
        "_check_type",
        "_spec_property_naming",
        "_path_to_item",
        "_configuration",
        "_visited_composed_classes",
    }

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ReportDataV3 - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            customer_code (str): Customer Code. [optional]  # noqa: E501
            customer_name (str): Customer name. [optional]  # noqa: E501
            dossier_number (str): Dossier number of the report. [optional]  # noqa: E501
            employee_code (str): Employee Code. [optional]  # noqa: E501
            employee_involved (str): Employee Involved. [optional]  # noqa: E501
            report_date_time (str): Report Date Time. [optional]  # noqa: E501
            executed_by (str): Executed By. [optional]  # noqa: E501
            report_result (str): Result. [optional]  # noqa: E501
            details (str): Details. [optional]  # noqa: E501
            details_message_code (str): Details Message Code. [optional]  # noqa: E501
            document_type (str): Document Type. [optional]  # noqa: E501
            document_type_code (str): Document Code. [optional]  # noqa: E501
            document_country (str): Document Country. [optional]  # noqa: E501
            document_number (str): Document Number. [optional]  # noqa: E501
            date_of_issue (str): Date of Issue. [optional]  # noqa: E501
            date_of_expiry (str): Date of Expiry. [optional]  # noqa: E501
            authority (str): Authority. [optional]  # noqa: E501
            first_name (str): First Name. [optional]  # noqa: E501
            name (str): Name. [optional]  # noqa: E501
            sex (str): Sex. [optional]  # noqa: E501
            date_of_birth (str): Date of Birth. [optional]  # noqa: E501
            place_of_birth (str): Place of Birth. [optional]  # noqa: E501
            personal_number (str): Personal Number. [optional]  # noqa: E501
            nationality (str): Nationality. [optional]  # noqa: E501
            photo_id_chip ([str]): Photo Id Chip. [optional]  # noqa: E501
            photo_holder ([str]): Photo Holder. [optional]  # noqa: E501
            id_document_front ([str]): Front Document. [optional]  # noqa: E501
            id_document_back ([str]): Back Document. [optional]  # noqa: E501
            other_document ([str]): Other document. [optional]  # noqa: E501
            signature_from_id_document (str): Signature from ID Document. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
